language: java
jdk:
  - openjdk11

sudo: required
services:
  - docker

jobs:
  include:

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: ./gradlew -Pversion=$TRAVIS_TAG release --scan --no-daemon -i

after_success:
  - bash <(curl -s https://codecov.io/bash)