server:
  port: 3289
  servlet:
    contextPath: /store

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  data:
    mongodb:
      uri: mongodb://localhost:27017/local